netConf:
   name: memoirs
   Port: '8888'
   cache-mode: redis  # 1.lru  2.redis
   cache-size: 1024

mysql:
  username: htc
  password: Htc123321
  path: 112.124.153.115
  port: 3309
  db-name: memoirs
  config: charset=utf8mb4&parseTime=true&loc=Asia%2fShanghai
  max-idle-conns: 20
  max-open-conns: 20
  log-mode: debug
  log-zap: true

# redis 配置
redis:
  addr: 127.0.0.1:6379               #101.132.251.60:6379
  password: 123456
  db: 0
  max-idle: 10 # 最大空闲链接数
  max-active: 0 # 数据库最大链接数，0表示不控制最大链接数
  idle-timeout: 120  //最大空闲时间

# logger
log:
  logFileDir: logs
  appName: app
  platform: local
  maxSize: 100
  maxBackups: 60
  maxAge: 30
  level: debug

jwt:
  sign-key: memoirs-key
  app-secret: abcdefghijklmnopqrstuvwxyz
  app-iss: localhost:8888
  expire-time: 604800
  buffer-time: 86400

## minio对象存储配置
minio:
  endpoint: 101.132.251.60:9000
  accessKey: minio
  secret: minio123321
  useSSL: false